name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    container: texlive/texlive:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build pdf
      run: make pdf

    - name: Upload pdf
      uses: actions/upload-artifact@v4
      with:
        name: thesis
        path: build/main.pdf
        retention-days: 14
